[tool.poetry]
name = "speech_node"
version = "0.0.1"
description = ""
authors = ["C. Thomas Brittain <cthomasbrittain@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
transformers = "^4.48.2"
torch = "^2.6.0"
torchaudio = "^2.6.0"
sounddevice = "^0.5.1"
llvmlite = "^0.44.0"
numba = "^0.61.0"
outetts = "^0.3.2"
fastapi = "^0.115.8"
rich = "^13.9.4"
pydub = "^0.25.1"
sentencepiece = "^0.2.0"
suno-bark = {git = "https://github.com/suno-ai/bark.git"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
