[tool.poetry]
name = "tts_worker"
version = "0.1.0"
description = ""
authors = ["C. Thomas Brittain <cthomasbrittain@hotmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10"
transformers = "^4.48.2"
torch = "^2.6.0"
torchaudio = "^2.6.0"
sounddevice = "^0.5.1"
llvmlite = "^0.44.0"
numba = "^0.61.0"
outetts = "^0.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
